# Generated by Django 3.0.8 on 2020-09-25 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Widgets',
            new_name='Widget',
        ),
    ]
